workflows:
  android-release-minor:
    name: Android Build & Firebase Distribution
    max_build_duration: 45
    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: release
    environment:
      vars:
        # FIREBASE_APP_ID: $FIREBASE_APP_ID
        # Ensure you store FIREBASE_TOKEN securely in Codemagic UI
      groups:
        - Firebase

    scripts:
      # - name: Install Dependencies
      #   script: yarn install

      - name: Set Yarn Classic
        script: |
          yarn set version classic

      - name: Install Dependencies
        script: |
          yarn install --no-immutable

      - name: Run Unit Tests
        script: yarn test || echo "Skipping tests"

      - name: Bump Minor Version
        script: |
          MAJOR=1
          MINOR=$(( BUILD_NUMBER ))
          echo "VERSION_CODE=$BUILD_NUMBER" >> $CM_ENV
          echo "VERSION_NAME=$MAJOR.$MINOR" >> $CM_ENV
          echo "✅ Bumped version to $MAJOR.$MINOR"

      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew

      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME

      - name: Upload to Firebase App Distribution
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > ${CM_BUILD_DIR}/firebase_service_account.json
           export GOOGLE_APPLICATION_CREDENTIALS=${CM_BUILD_DIR}/firebase_service_account.json

           echo "App ID: $FIREBASE_APP_ID"
           ls -lh android/app/build/outputs/apk/release/app-release.apk

           RELEASE_NOTES="Branch: $CM_BRANCH\nCommit: $CM_COMMIT"
           firebase appdistribution:distribute \
             android/app/build/outputs/apk/release/app-release.apk \
             --app $FIREBASE_APP_ID \
             --groups "qa" \
             --release-notes "$RELEASE_NOTES"

artifacts:
  - android/app/build/outputs/**/*.apk
