workflows:
  android-release-minor:
    name: Android Build & Firebase Distribution
    max_build_duration: 45
    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: release
    environment:
      vars:
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        # Ensure you store FIREBASE_TOKEN securely in Codemagic UI
      groups:
        - Firebase

    scripts:
      # - name: Install Dependencies
      #   script: yarn install

      - name: Set Yarn Classic
        script: |
          yarn set version classic

      - name: Install Dependencies
        script: |
          yarn install --no-immutable

      - name: Run Unit Tests
        script: yarn test || echo "Skipping tests"

      - name: Bump Minor Version
        script: |
          MAJOR=1
          MINOR=$(( BUILD_NUMBER ))
          echo "VERSION_CODE=$BUILD_NUMBER" >> $CM_ENV
          echo "VERSION_NAME=$MAJOR.$MINOR" >> $CM_ENV
          echo "✅ Bumped version to $MAJOR.$MINOR"

      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME

      - name: Upload to Firebase App Distribution
        script: |
          curl -sL firebase.tools | bash
          firebase appdistribution:distribute \
            app/build/outputs/apk/release/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers,qa-team" \
            --emails "adityaranjangudu98@gmail.com" \
            --release-notes "Branch: $CM_BRANCH, Commit: $CM_COMMIT" \
            --token $FIREBASE_TOKEN

artifacts:
  - android/app/build/outputs/**/*.apk
