#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test
# npm run typecheck
npx lint-staged

# Format only staged files (JS, TS, etc.)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|tsx|jsx|json)$')

if [ -n "$STAGED_FILES" ]; then
  echo "Formatting staged files with Prettier..."
  echo "$STAGED_FILES" | xargs npx prettier --write

  # Re-stage the formatted files
  echo "$STAGED_FILES" | xargs git add
fi
